name: Build LaTeX document
run-name: ${{ github.actor }} pushed a change that triggered compilation of lecture notes.
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          working_directory: wwu_book
          root_file: PoU.tex
          continue_on_error: true
      - name: Upload Lecture Notes PDF
        uses: actions/upload-artifact@v3
        with:
          name: PoU.pdf
          path: wwu_book/PoU.pdf
      - name: Upload Notes Compile Log
        uses: actions/upload-artifact@v3
        with:
          name: PoU.log
          path: wwu_book/PoU.log

