name: Build LaTeX document
run-name: ${{ github.actor }} pushed a change that triggered compilation of lecture notes.
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: wwu_book/PoU.tex
      - name: Upload PDF file
        uses: actions/upload-artifact@v3
        with:
          name: PDF
          path: wwu_book/PoU.pdf
