name: Compile Lecture Notes PDF (Artifact)
run-name: ${{ github.actor }} pushed a change that triggered the compilation of lecture notes.

on: 
  release:
  push:
#    paths:
#      - wwu_book

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Set up Environment
        run: echo "VERSION=$(grep -o '\\textbf{Working with uncertainty}\\\\ \\begin{small}.*\\end{small}' wwu_book/PoU.tex | grep -o 'v\d*.\d*')" >> $GITHUB_ENV
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          working_directory: wwu_book
          root_file: PoU.tex
          continue_on_error: true
      - name: Upload Lecture Notes PDF
        uses: actions/upload-artifact@v3
        with:
          name: PoU.pdf
          path: wwu_book/PoU.pdf
      - name: Upload Notes Compile Log
        uses: actions/upload-artifact@v3
        with:
          name: PoU.log
          path: wwu_book/PoU.log

